/*
	map.hpp is part of
	RED-ENGINE - An Object-Oriented game engine based on Allegro5
	Copyright (C) 2015 - 2016 Anthony REY

	This program is free software: you can redistribute it and/or modify
			it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
			but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef MAP_HPP
#define MAP_HPP

#include "red_engine/engine_core.hpp"
#include "red_engine/map.hpp"
#include "red_engine/collision_engine.hpp"
#include "player.hpp"

//This is the walkable map generated by the walkableMap Generator
class PlayerMap : public RedEngine::Map {

    public :
        PlayerMap(std::string mapName, std::vector<RedEngine::MapAtom ***> atomsByLayers,
                  int xmax, int ymax);
        ~PlayerMap();
        void setPlayerComponent(PlayerComponent* playerComponent);
        void init();
        void update();
        void draw();

    private:
        PlayerComponent* playerComponent;
        int x_offset = 0;
        int y_offset = 0;
        ALLEGRO_TRANSFORM camera_transform;
    };

class WalkableMapGenerator : public RedEngine::IGenerator {
    public:
        WalkableMapGenerator();
        RedEngine::Map* generate(std::string mapName,
                                    std::vector<RedEngine::MapAtom***> atomsByLayers, int xmax, int ymax);
};

#endif //Red-_MAP_HPP
