//
// Created by Anthony REY on 20/12/2015.
//

#ifndef MAP_HPP
#define MAP_HPP

#include "red_engine/engine_core.hpp"
#include "red_engine/map.hpp"
#include "red_engine/collision_engine.hpp"
#include "player.hpp"

//This is the walkable map generated by the walkableMap Generator
class PlayerMap : public RedEngine::Map {

    public :
        PlayerMap(std::string mapName, std::vector<RedEngine::MapAtom ***> atomsByLayers,
                  int xmax, int ymax);
        ~PlayerMap();
        void setPlayerComponent(PlayerComponent* playerComponent);
        void init();
        void update();
        void draw();

    private:
        PlayerComponent* playerComponent;
        int x_offset = 0;
        int y_offset = 0;
        ALLEGRO_TRANSFORM camera_transform;
    };

class WalkableMapGenerator : public RedEngine::IGenerator {
    public:
        WalkableMapGenerator();
        RedEngine::Map* generate(std::string mapName,
                                    std::vector<RedEngine::MapAtom***> atomsByLayers, int xmax, int ymax);
};

#endif //Red-_MAP_HPP
